# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['pollution_analysis',
 'pollution_analysis.config',
 'pollution_analysis.src',
 'pollution_analysis.utils']

package_data = \
{'': ['*']}

install_requires = \
['geopandas>=0.9.0,<0.10.0',
 'open-geo-engine @ git+https://github.com/AQ-AI/open-geo-engine.git@main',
 'pandas>=1.3.5,<2.0.0',
 'requests>=2.26.0,<3.0.0']

setup_kwargs = {
    'name': 'pollution-analysis',
    'version': '0.1.0',
    'description': '',
    'long_description': None,
    'author': 'ChristinaLast',
    'author_email': 'christina.last@outlook.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
